all: compile run-delete-all-environment-variable

compile: main.c
	gcc main.c -o main.out

run-delete-specific-environment-variable: main.out
	./main.out

run-delete-all-environment-variable: main.out
	./main.out
